apiVersion: kontinuum.nardis.io/v1alpha1
kind: HubCluster
metadata:
  labels:
    app.kubernetes.io/name: kontinuum
    app.kubernetes.io/managed-by: kustomize
  name: hubcluster-sample
spec:
  # TODO(user): Add fields here
